#!/bin/sh
#
# ISO9660 image phase 8: rootfs script
#
LFS=/mnt/kjxh
#LFS_UUID=$()
LFS_UUID=/dev/sda1/
QCOW_FILE="./utils/storage/kjxh.qcow2"

packaging() {

printf "=============|> [STEP 8]: rootfs script \n============="

groupadd kjx
useradd -sR /bin/bash -g kjx -m -k /dev/null kjx

# get software
wget --input-file=./artifacts/wget-list-sysv.txt --continue --directory-prefix="$LFS/sources"
# =============================
# runit/runsv/runsvdir stup
mkdir -p rootfs/etc/runit
mkdir -p rootfs/etc/runit/runsvdir/default
mkdir -p rootfs/service

# runit: symbolic link convention
ln -s /etc/runit/runsvdir/default/ rootfs/service/

# runit: service scripts, get a shell
mkdir -p rootfs/etc/runit/runsvdir/default/getty-tty1

cat <<EOF > rootfs/etc/runit/runsvdir/default/getty-tty1/run
#!/bin/sh
#
exec /sbin/getty 38400 tty1
EOF
chmod +x rootfs/etc/runit/runsvdir/default/getty-tty1/run

# runit: initialization
cat <<EOF > rootfs/etc/runit/1

# ============================


RUN cat > ./init <<"INIT_EOF"
#!/bin/busybox sh

# mount filesystems
mount -t devtmpfs   devtmpfs    /dev
mount -t proc       none        /proc
mount -t sysfs      none       /sys
mount -t tmpfs      tmpfs       /tmp

# mount tracefs and securityfs pseudo-filesystems
mount -t tracefs tracefs /sys/kernel/tracing/
mount -t debugfs debugfs /sys/kernel/debug/
mount -t securityfs securityfs /sys/kernel/security/
EOF && \
#
#
#
# set up hostname
echo "kjx" > /etc/hostname && hostname -F /etc/hostname

# bring up the connection
/sbin/ip link set lo up                         # bring up loopback interface
/sbin/ip link set eth0 up                       # bring up ethernet interface
/sbin/ip addr add 192.168.0.27 eth0             # static ipv4 assignment

# alternate method, built-in inside busybox
#udhcpc -i eth0 # dynamic ipv4 assignment

# ================================


sysctl -w kernel.printk="2 4 1 7"

# sets up BRK keyboard
setxkbmap -model abnt2 -layout br -variant abnt2
echo && echo

# get rootfs UUID from kernel parameters on /proc/cmdline
ROOTFS=$(cat /proc/cmdline | awk -F= 'NR==1 {print $4}' | awk '{print $1}')
exec /bin/busybox switch_root -c /dev/console $ROOTFS /usr/bin/init

current_commit_hash = subprocess.run(["git", "rev-parse", "--short", "HEAD"], stdout=subprocess.PIPE, text=True)
current_commit_hash = current_commit_hash.stdout.strip()
print ("\033[93;1;4mCurrent Commit Hash    : " + current_commit_hash + "\033[0m")

cat << 'asciiart'
 .-"``"-.
/  _.-` (_) `-._
\   (_.----._)  /
 \     /    \  /
  `\  \____/  /`
    `-.____.-`      __     _
     /      \      / /__  (_)_ __
    /        \    /  '_/ / /\ \ /
   /_ |  | _\    /_/\_\_/ //_\_\
     |  | |          |___/         deomorxsy/kjx
     |__|__|  ----------------------------------------------
     /_ | _\   Reboot (01.00.0, ${GIT_CONTAINERFILE_HASH})
              ----------------------------------------------
asciiart

# get a shell
sh

asciiart

printf "Boot took $(cut -d' ' -f1 /proc/uptime) seconds btw\n"

# get a shell
sh
INIT_EOF



EOF

# start fakeroot
fakeroot
# apk-tools
cp -r ./artifacts/deps mount-point-fuse/bin
chmod +x ./mount-point-fuse/bin
ln -s ./artifacts/mount-point-fuse/bin/x mount-point-fuse/sbin/x

# soft links
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /sbin/apk
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /usr/bin/apk
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /usr/sbin/apk

. ./scripts/virt-platforms/firecracker-startup.sh
. ./scripts/virt-platforms/gvisor-startup.sh
. ./scripts/virt-platforms/kata-startup.sh
#cp -r ./artifacts/deps/mount-point-fuse/
exit # exit fakeroot
EOF

}




# Alternative script ================
#
previous_packaging() {


groupadd kjx
useradd -sR /bin/bash -g kjx -m -k /dev/null kjx

# get software (libcap, k3s)
wget --input-file=wget-list-static.txt --continue --directory-prefix="$LFS/sources"

# start fakeroot
fakeroot
# apk-tools
cp -r ./artifacts/deps mount-point-fuse/bin
chmod +x ./mount-point-fuse/bin
ln -s ./artifacts/mount-point-fuse/bin/x mount-point-fuse/sbin/x

# soft links
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /sbin/apk
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /usr/bin/apk
sudo ln -s ./artifacts/mount-point-fuse/usr/local/bin/apk /usr/sbin/apk

. ./scripts/virt-platforms/firecracker-startup.sh
. ./scripts/virt-platforms/gvisor-startup.sh
. ./scripts/virt-platforms/kata-startup.sh
#cp -r ./artifacts/deps/mount-point-fuse/
exit # exit fakeroot
}

packaging
