#version: "3.8"
services:
  libbpf:
    environment:
      - git_hash
    build:
      context: "."
      dockerfile: "./trace/libbpf/Dockerfile"
      tags:
        - "localhost:5000/libbpf:latest"
    stop_signal: SIGINT
  ayaya:
    environment:
      - git_hash
    build:
      context: "."
      dockerfile: "./trace/ayaya/Dockerfile"
      tags:
        - "localhost:5000/export_bee:latest"
    stop_signal: SIGINT
  isogen:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      tags:
        - "localhost:5000/isogen:latest"
    stop_signal: SIGINT
  iso_system_test:
    build:
      context: "."
      dockerfile: "./tests/Dockerfile"
      tags:
        - "localhost:5000/iso-system-test:01"
    stop_signal: SIGINT
  mock_ist:
    build:
      context: "."
      dockerfile: "./tests/Dockerfile"
      tags:
        - "localhost:5000/mock_ist:latest"
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
    stop_signal: SIGINT
  initramfs:
    environment:
      - git_hash
    build:
      context: "."
      dockerfile: "./assets/busybox/Dockerfile"
      args:
        GIT_COMPOSE_SHA: "${GIT_COMMIT_HASH:-none}"
      tags:
        - "localhost:5000/initramfs:latest"
    stop_signal: SIGINT
  kernel:
    build:
      context: "./assets/kernel/"
      tags:
        - "localhost:5000/linux_build:latest"
    stop_signal: SIGINT
  exporter:
    build:
      context: "./assets/ebpf_exporter/"
      # Dockerfile's location is relative to the context field (the base directory).
      dockerfile: "../../trace/exporter-libbpfgo/Dockerfile"
      tags:
        - "localhost:5000/exporter-static:latest"
    stop_signal: SIGINT
  # =======================
  # AWS provider emulation
  # =======================
  tofu_deps:
    build:
      context: "."
      dockerfile: "./deploy/Dockerfile.lstf"
      tags:
        - "localhost:5000/tofu_deps:latest"
  localstack:
    build:
      tags:
        - "localhost:5000/localstack:latest"
    depends_on:
      - tofu_deps
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      #- DEBUG=${DEBUG:-0}
      - DEBUG=$${1:-0}
      - SERVICES=ec2,s3,vpc
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


