FROM golang:1.24-alpine3.22 AS builder

COPY ./scripts/sandbox/kata-startup.sh /app/scripts/sandbox/kata-startup.sh
COPY ./scripts/packages/demo-replased.sh /app/scripts/packages/demo-replased.sh
COPY ./artifacts/microvms/kata-static-3.24.0-amd64.tar.zst /helper

ARG GIT_CONTAINERFILE_HASH
ENV GIT_CONTAINERFILE_HASH=${GIT_COMPOSE_SHA}

WORKDIR /app/

RUN <<EOF

apk upgrade && apk update && \
    apk add cni-plugins cri-tools containerd \
    gcompat \
    git zstd

#go get github.com/containernetworking/plugins
#go get github.com/kubernetes-incubator/cri-tools

ls -allhtr

#MODE="build" . ./scripts/sandbox/kata-startup.sh
EOF

RUN <<EOF

if ! (MODE="kata-tarball" . /app/scripts/sandbox/kata-startup.sh); then
    printf "\n|> Error: could not execute the [kata-tarball] function from the kata-startup.sh shellscript. Exiting now...\n\n"
    return 1
fi
printf "\n|> Succesfully run [kata-tarball] from kata-startup.sh. Proceeding..."

if ! (ls -allhtr "/kata-tarball-pkg.tar.gz"); then
    echo "|> kata-tarball NOT FOUND. EXITING..."
    return 1
fi
echo "|> FOUND THE SO TARBALL \O/ ...[PASSED]"

EOF

RUN <<EOF

if ! (MODE="kata-bin" . /app/scripts/sandbox/kata-startup.sh); then
    echo "|> Error: could not run the [set_kata_bin] function from the [kata-startup.sh] shellscript. Exiting now..."
    return 1
fi
    echo "|> Sucessfully ran the [set_kata_bin] function from the [kata-startup.sh] shellscript. Proceeding..."

if ! (ls -allhtr "/kata-tarball-pkg.tar.gz"); then
    echo "|> kata-tarball NOT FOUND. EXITING..."
    return 1
fi
echo "|> FOUND THE SO TARBALL \O/ ...[PASSED]"

EOF


FROM alpine:3.22 AS relay

WORKDIR /app
COPY --from=builder /kata-bin-pkg.tar.gz .
COPY --from=builder /kata-tarball-pkg.tar.gz .

RUN echo "done!!!"

ENTRYPOINT ["/bin/sh"]
