apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-containers
handler: kata
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-gvisor
spec:
  runtimeClassName: kata-containers
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "50Mi" # min memory allowed
        cpu: "100m"    # min cpu allowed
      limits:
        memory: "100Mi" # max memory allowed
        cpu: "200m"     # max cpu allowed
  nodeName: user
