name: aya-rs

# This rule triggers when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build OCI image
        run: |
          docker run  -d -p 5000:5000 --name registry registry:2.7
          # env git_hash env goes into the compose.yml
          docker compose -f ./compose.yml --progress=plain build libbpf_core
          docker push localhost:5000/libbpf_core:latest
          #podman build -t bubo_builder:latest -f ./utils/busybox/Dockerfile


      - name: Retrieve artifact from OCI image
        run: |
          mkdir -p ${{ github.workspace }}/artifacts/libbpf-examples/
          docker create --name libbpf_core localhost:5000/libbpf_core:latest
          docker cp ${{ github.workspace }}/trace/libbpf-core/examples/ libbpf_core:./app/
          docker run -it --name libbpf_core -d --entrypoint="/bin/sh" localhost:5000/haskell_exs:latest -c 'mkdir -p /artifacts/libbpf-examples/; tar -czf /artifacts/libbpf-examples/bpfcore_examples.tar.gz'
          docker cp libbpf_core:/artifacts/libbpf-examples/bpfcore_examples.tar.gz ${{ github.workspace }}/artifacts/libbpf-examples/
          echo done!!

      - name: Archive the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bubo
          # image size: 8.48MB
          # artifact size: 829.6K
          path: ${{ github.workspace }}/artifacts/bpfcore_examples.tar.gz
