name: aya-rs

# This rule triggers when the workflow will run
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build OCI image
        run: |
          make ayaya


     # - name: Build OCI image
     #   run: |
     #     docker run  -d -p 5000:5000 --name registry registry:3.0
     #     # env git_hash env goes into the compose.yml
     #     docker compose -f ./compose.yml --progress=plain build ayaya
     #     docker push localhost:5000/aya-rs:latest
     #     #podman build -t bubo_builder:latest -f ./utils/busybox/Dockerfile


     # - name: Retrieve artifact from OCI image
     #   run: |
     #     mkdir -p "\${{ github.workspace }}/artifacts/ayaya/examples/"
     #     docker create --name ayaya localhost:5000/aya_rs:latest
     #     #docker cp "\${{ github.workspace }}/trace/ayaya/examples/" ayaya:./app/
     #     # run OCI container with a volume to give the container context before the build, then copy artifacts
     #     docker run -it \
     #         --name ayaya \
     #         -v "\${{ github.workspace }}/artifacts/ayaya/examples/:/app/:ro" \
     #         -d \
     #         --entrypoint="/bin/sh" \
     #         localhost:5000/aya_rs:latest -c 'mkdir -p /hmm && tar -czf /hmm/aya-rs_examples.tar.gz /home/aya/app/'
     #     docker cp ayaya:/artifacts/ayaya/examples/aya-rs_examples.tar.gz ${{ github.workspace }}/artifacts/ayaya/examples
     #     echo done!!

     # - name: Archive the build artifact
     #   uses: actions/upload-artifact@v4
     #   with:
     #     name: aya-rs_examples
     #     # image size: 8.48MB
     #     # artifact size: 829.6K
     #     path: ${{ github.workspace }}/artifacts/aya-rs_examples.tar.gz
