name: qemu distro builder

# This rule triggers when the workflow will run
on:
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
      FETCH_ARTIFACT: ${{ secrets.FETCH_ARTIFACT }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}


      - name: build the rootfs for the qonq builder
        run: |
          . ./scripts/qonq.sh -fq


      - name: Archive the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qonq_ssh_rootfs
          # image size: 8.48MB
          # artifact size: 829.6K
          path: ${{ github.workspace }}/artifacts/ssh-rootfs/ssh-rootfs-revised.cpio_*.gz
